### ISSUE TITLE
Closing brackets between tags

### ISSUE THREAD

**Issue by tvarsis** [formulahendry/vscode-auto-close-tag#2]
Example:

Typing `<div>` and tab Auto Close Tag inserts `<div></div>` and places the cursor in between. If I here insert a { no closing curly brace is inserted and it looks like this `<div>{</div>`. However, if i add a space after and then move the cursor back one step the closing curly brace gets inserted correctly and the result looks like this `<div>{} </div>`

Not sure if this is a limitation in how VS Code auto closing works, but it could however be fixed pretty easy by letting this plugin insert a space after the cursor on inserting the closing html tag.

**Comment by formulahendry** [comment]
@tvarsis Thanks for your feedback! :smile:  But for this scenario, I think this would be the limitation of VS Code. I suggest you open an issue to [VS Code](https://github.com/Microsoft/vscode/issues) and let VS Code make improvement on this. I don't want make an space between opening and closing tags since an extra space will impact the rendering of the html document. It will break the current behavior for other users.
